### ISSUE TITLE
The timing tab's popover appear on all charts at the same time

### ISSUE THREAD

**Issue by oleiade** [grafana/xk6-dashboard#56] opened 2023-08-28 14:48 UTC
I have noticed as I used the timing tab, that when hovering over a single chart, the popover activates for all of them, leading to an army of popups over the screen as displayed in the following screenshot:
![Screenshot 2023-08-28 at 16 47 19](https://github.com/grafana/xk6-dashboard/assets/690867/208a1b1b-d005-4bbb-8d2e-1c81e69d5da4)

I assume this is a bug, but let me know otherwise 😸

**Comment by szkiba** [comment] 2023-08-28 15:05
"this is not a bug but a feature" :)
I thought that if someone examines the specific value on one of the charts, they probably want to see the values of the other charts at the same time. I am at least curious about the other values....

**Comment by oleiade** [comment] 2023-09-05 15:25
In hindsight, I do think this a good idea indeed 👍🏻 

We will probably polish it with designers/fontend engineers, but you're right, as a user, I realize this is valuable, and probably the simplest UX for the job 🙇🏻

**Comment by szkiba** [comment] 2023-10-03 13:01
Fixed in [v0.6.0](https://github.com/grafana/xk6-dashboard/releases/tag/v0.6.0)

**Closed by szkiba** 2023-10-03 13:01 UTC
Labels: bug
